apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "saga-pattern.fullname" . }}-secrets
  labels:
    {{- include "saga-pattern.labels" . | nindent 4 }}
stringData:
  REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
  ORCHESTRATOR_DATABASE_URL: {{ .Values.secrets.orchestratorDatabaseUrl | quote }}
  ORDERS_DATABASE_URL: {{ .Values.secrets.ordersDatabaseUrl | quote }}
  PAYMENTS_DATABASE_URL: {{ .Values.secrets.paymentsDatabaseUrl | quote }}
  INVENTORY_DATABASE_URL: {{ .Values.secrets.inventoryDatabaseUrl | quote }}
